resource_types:
  - name: registry-image
    type: registry-image
    source:
      repository: concourse/registry-image-resource
    defaults:
      registry_mirror:
        host: kowan-soko.toujou.systems
        username: ((kowan-soko-toujou-systems.username))
        password: ((kowan-soko-toujou-systems.password))
  - name: pull-request
    type: registry-image
    source:
      repository: spatialbuzz/gitea-pull-request-resource
  - name: git
    type: registry-image
    source:
      repository: concourse/git-resource
      tag: 1.14.5-alpine
    defaults:
      private_key: ((ssh-key.id_rsa))
  - name: hangouts-resource
    type: registry-image
    source:
      repository: cloudinn/concourse-hangouts-resource
      tag: latest

resources:
  - name: hangouts
    type: hangouts-resource
    source:
      webhook_url: ((kowan-soko-toujou-systems.chat_webhook_url))
      post_url: true
  - name: ci
    type: git
    icon: git
    source:
      uri: git@code.dfau.de:toujou/ci.git
      branch: main
      private_token: ((code-dfau-de.private_token))
      private_key: ((ssh-key.id_rsa))
  - name: repo-pr
    type: pull-request
    icon: git
    source:
      uri: git@code.dfau.de:toujou/{{lowercase_projectname}}.git
      private_token: ((code-dfau-de.private_token))
      private_key: ((ssh-key.id_rsa))
      skip_ssl_verification: true
  - name: master-push
    type: git
    icon: git
    source:
      uri: git@code.dfau.de:toujou/{{lowercase_projectname}}.git
      branch: master
      private_token: ((code-dfau-de.private_token))
      private_key: ((ssh-key.id_rsa))
      skip_ssl_verification: true

jobs:
  - name: run-tests-pr
    serial: false
    plan:
      - in_parallel:
          - get: ci
          - get: workspace
            resource: repo-pr
            trigger: true
      - put: repo-pr
        params:
          repository: workspace
          status: pending
          build_label: Backend Tests
      - &build
        task: composer-install
        file: ci/tasks/php-command-with-ssh.yml
        vars:
          phpversion: "7.4"
          workdir: workspace
          command: composer install -n --no-progress
        params:
          COMPOSER_AUTH: ((code-dfau-de.COMPOSER_AUTH))
      - in_parallel: &qa
          - task: run-codingstandards
            file: ci/tasks/php-command-with-ssh.yml
            vars:
              phpversion: "7.4"
              workdir: workspace
              command: ./etc/scripts/checkCodingStandards.sh
          - task: run-typoscript-lint
            file: ci/tasks/php-command-with-ssh.yml
            vars:
              phpversion: "7.4"
              workdir: workspace
              command: ./.Build/bin/typo3-typoscript-lint
          - task: run-yaml-lint
            file: ci/tasks/php-command-with-ssh.yml
            vars:
              phpversion: "7.4"
              workdir: workspace
              command: ./.Build/bin/yaml-lint Configuration --parse-tags
          - task: run-unit-tests
            privileged: true
            file: ci/tasks/docker-in-docker.yml
            vars:
              workdir: workspace
              command: |
                mkdir -p ./.Build/Web/typo3conf/ext/ && ln -s "$(pwd)" ./.Build/Web/typo3conf/ext/toujou_{{snake_case_projectname}}
                ./etc/scripts/runTests.sh -s unit -p 7.4
          - task: run-functional-tests
            privileged: true
            file: ci/tasks/docker-in-docker.yml
            vars:
              workdir: workspace
              command: |
                mkdir -p ./.Build/Web/typo3conf/ext/ && ln -s "$(pwd)" ./.Build/Web/typo3conf/ext/toujou_{{snake_case_projectname}}
                ./etc/scripts/runTests.sh -s functional -p 7.4
    on_failure:
      put: repo-pr
      params:
        repository: workspace
        status: failure
        build_label: Backend Tests
    on_success:
      put: repo-pr
      params:
        repository: workspace
        status: success
        build_label: Backend Tests

  - name: run-tests-master
    serial: false
    plan:
      - in_parallel:
          - get: ci
          - get: workspace
            resource: master-push
            trigger: true
      - *build
      - in_parallel: *qa
    on_failure:
      try:
        put: hangouts
        params:
          message: Broken tests on master!
