name: Frontend-CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Resources/Public
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: './Resources/Public/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Info
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          npm list

      - name: Eslint
        run: npm run lint

      - name: Run tests
        run: npm run test
