name: Republish-Resources-CI

on:
  push:
    branches: [ 'master' ]
    paths:
      - 'Resources/Public/**'
      - '!Resources/Public/build/**'
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Resources/Public
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '16.4']

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: './Resources/Public/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Info
        run: |
          echo "Node Version: $(node --version)"
          echo "NPM Version: $(npm --version)"
          npm list

      - name: Build
        run: |
          npm run build:all
          git add .

          git config --global user.name "ci"
          git config --global user.email "ci@dfau.dev"

          git commit -m "build: republish resources [ci skip]" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

